image_width: 160
image_height: 120
camera_name: tim160
camera_matrix:
  rows: 3
  cols: 3
  data: [146.12, 0, 80, 0, 148.88, 60, 0, 0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [146.12, 0, 80, 0, 0, 148.88, 60, 0, 0, 0, 1, 0]
